<?php

declare(strict_types=1);

use Magento\Framework\Escaper;

/**
 * @var Escaper $escaper
 */
?>
<div
    class="field limiter flex items-center order-3 sm:order-2 md:order-3 lg:order-2 col-span-2 justify-end"
    x-data
>
    <template x-if="$store.meilisearch.hasMultipleLimiterOptions()">
        <div class="control">
            <label class="text-sm label">
                <span
                    class="mr-2"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Show items per page')) ?>"
                >
                    <?= $escaper->escapeHtml(__('Show')) ?>
                </span>

                <select
                    class="form-select limiter-options"
                    @change="$store.meilisearch.changePerPageFromEvent"
                >
                    <template
                        x-for="limit in $store.meilisearch.limiterOptions()"
                        :key="limit"
                    >
                        <option :value="limit" x-text="limit"></option>
                    </template>
                </select>
            </label>
        </div>
    </template>
</div>
