<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Escaper;
use Walkwizus\MeilisearchFrontend\ViewModel\Ssr;

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HeroiconsOutline $heroicons */
/** @var Ssr $ssr */

$heroicons = $viewModels->require(HeroiconsOutline::class);
$ssr = $viewModels->require(Ssr::class);
$config = $ssr->getConfig();
$availableSortBy = $config['availableSortBy'] ?? [];
$selectedSortBy = $ssr->getSortBy();
$isDescending = $ssr->isDescending();
?>
<div
    class="toolbar-sorter sorter flex items-center order-1 col-span-3 sm:col-span-6 md:col-span-3 lg:col-span-6 justify-end"
    x-data
>
    <label class="inline-block mr-3">
        <select
            data-role="sorter"
            name="sorter"
            class="form-select sorter-options"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Sort By')) ?>"
            @change="$store.meilisearch.setSortBy($event.target.value)"
        >
            <?php foreach ($availableSortBy as $code => $label): ?>
                <option
                    value="<?= $escaper->escapeHtmlAttr((string) $code) ?>"
                    <?= ((string) $code === $selectedSortBy) ? 'selected' : '' ?>
                >
                    <?= $escaper->escapeHtml((string) $label) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </label>
    <button
        x-show="$store.meilisearch.state.isDescending"
        title="<?= $escaper->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
        type="button"
        class="action sorter-action sort-desc"
        :disabled="!$store.meilisearch.state.sortBy"
        :class="!$store.meilisearch.state.sortBy ? 'opacity-60 cursor-not-allowed' : ''"
        @click.prevent="$store.meilisearch.toggleSortDirection()"
    >
        <?= $heroicons->sortAscendingHtml('', 24, 24, ['aria-hidden' => 'true']); ?>
    </button>
    <button
        x-show="!$store.meilisearch.state.isDescending"
        type="button"
        title="<?= $escaper->escapeHtmlAttr(__('Set Descending Direction')) ?>"
        class="action sorter-action sort-asc"
        :disabled="!$store.meilisearch.state.sortBy"
        :class="!$store.meilisearch.state.sortBy ? 'opacity-60 cursor-not-allowed' : ''"
        @click.prevent="$store.meilisearch.toggleSortDirection()"
    >
        <?= $heroicons->sortDescendingHtml('', 24, 24, ['aria-hidden' => 'true']); ?>
    </button>
</div>
