<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Walkwizus\MeilisearchFrontend\ViewModel\Ssr;

/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HeroiconsOutline $heroicons */
/** @var HyvaCsp $hyvaCsp */
/** @var Ssr $ssr */

$hyvaCsp = $viewModels->require(HyvaCsp::class);
$heroicons = $viewModels->require(HeroiconsOutline::class);
$ssr = $viewModels->require(Ssr::class);
$config = $ssr->getConfig();
$availableSortBy = $config['availableSortBy'] ?? [];
$selectedSortBy = $ssr->getSortBy();
$isDescending = $ssr->isDescending();
?>
<div
    class="toolbar-sorter sorter flex items-center order-1 col-span-3 sm:col-span-6 md:col-span-3 lg:col-span-6 justify-end"
    x-data="initMeilisearchSorter"
>
    <label class="inline-block mr-3">
        <select
            data-role="sorter"
            name="sorter"
            class="form-select sorter-options"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Sort By')) ?>"
            @change="onSortChange"
        >
            <?php foreach ($availableSortBy as $code => $label): ?>
                <option
                    value="<?= $escaper->escapeHtmlAttr((string) $code) ?>"
                    <?= ((string) $code === $selectedSortBy) ? 'selected' : '' ?>
                >
                    <?= $escaper->escapeHtml((string) $label) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </label>
    <button
        x-show="$store.meilisearch.state.isDescending"
        title="<?= $escaper->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
        type="button"
        class="action sorter-action sort-desc"
        :disabled="$store.meilisearch.hasNoSortBy()"
        :class="$store.meilisearch.sortBtnDisabledClass()"
        @click.prevent="$store.meilisearch.toggleSortDirection"
    >
        <?= $heroicons->sortAscendingHtml('', 24, 24, ['aria-hidden' => 'true']); ?>
    </button>
    <button
        x-show="$store.meilisearch.isAscending()"
        type="button"
        title="<?= $escaper->escapeHtmlAttr(__('Set Descending Direction')) ?>"
        class="action sorter-action sort-asc"
        :disabled="$store.meilisearch.hasNoSortBy()"
        :class="$store.meilisearch.sortBtnDisabledClass()"
        @click.prevent="$store.meilisearch.toggleSortDirection"
    >
        <?= $heroicons->sortDescendingHtml('', 24, 24, ['aria-hidden' => 'true']); ?>
    </button>
</div>

<script>
    function initMeilisearchSorter() {
        return {
            onSortChange() {
                this.$store.meilisearch.setSortBy(this.$event.target.value);
            }
        }
    }
    window.addEventListener('alpine:init', () => Alpine.data('initMeilisearchSorter', initMeilisearchSorter), {once: true})
</script>
<?php $hyvaCsp->registerInlineScript() ?>
