<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Catalog\Block\Product\ProductList\Toolbar;
use Magento\Framework\Escaper;

/** @var Toolbar $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var HyvaCsp $hyvaCsp */
$hyvaCsp = $viewModels->require(HyvaCsp::class);
?>

<?php if ($block->isEnabledViewSwitcher()): ?>
    <?php $modes = $block->getModes(); ?>
    <?php if ($modes && count($modes) > 1): ?>
        <nav
            class="modes invisible md:visible flex justify-center gap-1 mr-2 items-center px-2 py-2 rounded-md border border-gray-300 bg-white text-sm leading-5
                w-20 order-1 col-span-1 sm:col-span-2 md:col-span-1 lg:col-span-2"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Products view mode')) ?>"
            x-data="initMeilisearchViewmode"
        >
            <style>
                .modes-mode.mode-grid {
                    background-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2V6zM14 6a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V6zM4 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2H6a2 2 0 01-2-2v-2zM14 16a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z" /></svg>');
                }

                .modes-mode.mode-list {
                    background-image: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"> <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 10h16M4 14h16M4 18h16" /></svg>');
                }
            </style>
            <?php foreach ($block->getModes() as $code => $label): ?>
                <?php $mode = strtolower($code); ?>
                <button
                    type="button"
                    class="modes-mode w-6 h-6 mode-<?= $escaper->escapeHtmlAttr($mode) ?>"
                    title="<?= $escaper->escapeHtmlAttr($label) ?>"
                    data-role="mode-switcher"
                    data-value="<?= $escaper->escapeHtmlAttr($mode) ?>"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Products view mode - %1', $label)) ?>"
                    @click="setViewMode"
                    :class="viewModeButtonClass()"
                    :disabled="isActiveMode()"
                ></button>
            <?php endforeach; ?>
        </nav>
    <?php else: ?>
        <div class="modes w-20 order-1 col-span-1 sm:col-span-2 md:col-span-1 lg:col-span-2"></div>
    <?php endif; ?>
<?php endif; ?>

<script>
    function initMeilisearchViewmode() {
        return {
            setViewMode() {
                this.$store.meilisearch.setViewMode(this.$el.dataset.value);
            },

            isActiveMode() {
                return this.$store.meilisearch.viewModeState.mode === this.$el.dataset.value;
            },

            viewModeButtonClass() {
                const mode = this.$el.dataset.value;
                const active = this.$store.meilisearch.viewModeState.mode === mode;
                const base = 'modes-mode w-6 h-6 mode-' + mode;
                return active ? base + ' active' : base + ' opacity-50 hover:opacity-100';
            }
        }
    }
    window.addEventListener('alpine:init', () => Alpine.data('initMeilisearchViewmode', initMeilisearchViewmode), {once: true})
</script>
<?php $hyvaCsp->registerInlineScript() ?>
